name: Format Code with clang-format

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]  

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - name: Install clang-format and sed
      run: sudo apt-get update && sudo apt-get install -y clang-format sed

    - name: Remove Chinese comments
      run: |
        find . -type f \( -name "*.cpp" -o -name "*.h" \) -exec sed -i 's/\/\/[^\n]*[\x4e00-\x9fa5][^\n]*//g' {} \;

    - name: Run clang-format
      run: find . -type f -name "*.cpp" -o -name "*.h" | xargs clang-format -i

    - name: Check for modified files
      id: git-check
      run: |
        git diff --exit-code || echo "modified=true" >> $GITHUB_OUTPUT
      shell: bash

    - name: Commit formatted files
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "format"
        git push